# Needs the `build-pdf.sh` script
name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        run: |
          chmod +x build-pdf.sh
          ./build-pdf.sh
        shell: bash
      - uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: main.pdf
